AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: NHS Appointment Booking Prototype - Serverless Backend

Globals:
  Function:
    Timeout: 30
    Runtime: python3.11
    Environment:
      Variables:
        APPOINTMENTS_TABLE: !Ref AppointmentsTable
        PATIENTS_TABLE: !Ref PatientsTable
        PRACTICES_TABLE: !Ref PracticesTable
        USER_POOL_ID: !Ref UserPool
        USER_POOL_CLIENT_ID: !Ref UserPoolClient
        REGION: !Ref AWS::Region

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name

Resources:
  # Cognito User Pool for Authentication
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub '${Environment}-nhs-appointment-users'
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
        - Name: nhs_number
          AttributeDataType: String
          Required: false
        - Name: role
          AttributeDataType: String
          Required: false

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: !Sub '${Environment}-nhs-appointment-client'
      GenerateSecret: false
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
        - USER_PASSWORD_AUTH

  # DynamoDB Tables
  AppointmentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${Environment}-appointments'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: appointment_id
          AttributeType: S
        - AttributeName: patient_id
          AttributeType: S
        - AttributeName: practice_id
          AttributeType: S
        - AttributeName: appointment_date
          AttributeType: S
      KeySchema:
        - AttributeName: appointment_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: PatientIndex
          KeySchema:
            - AttributeName: patient_id
              KeyType: HASH
            - AttributeName: appointment_date
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: PracticeIndex
          KeySchema:
            - AttributeName: practice_id
              KeyType: HASH
            - AttributeName: appointment_date
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  PatientsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${Environment}-patients'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: patient_id
          AttributeType: S
        - AttributeName: nhs_number
          AttributeType: S
      KeySchema:
        - AttributeName: patient_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: NHSNumberIndex
          KeySchema:
            - AttributeName: nhs_number
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  PracticesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${Environment}-practices'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: practice_id
          AttributeType: S
      KeySchema:
        - AttributeName: practice_id
          KeyType: HASH

  # API Gateway
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt UserPool.Arn

  # Lambda Functions
  CreateAppointmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/appointments/
      Handler: create_appointment.lambda_handler
      Events:
        CreateAppointment:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /appointments
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AppointmentsTable
        - DynamoDBReadPolicy:
            TableName: !Ref PatientsTable
        - DynamoDBReadPolicy:
            TableName: !Ref PracticesTable

  GetAppointmentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/appointments/
      Handler: get_appointments.lambda_handler
      Events:
        GetAppointments:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /appointments
            Method: get
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref AppointmentsTable

  UpdateAppointmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/appointments/
      Handler: update_appointment.lambda_handler
      Events:
        UpdateAppointment:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /appointments/{appointment_id}
            Method: put
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AppointmentsTable

  DeleteAppointmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/appointments/
      Handler: delete_appointment.lambda_handler
      Events:
        DeleteAppointment:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /appointments/{appointment_id}
            Method: delete
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AppointmentsTable

  CreatePatientFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/patients/
      Handler: create_patient.lambda_handler
      Events:
        CreatePatient:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /patients
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PatientsTable

  GetPatientFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/patients/
      Handler: get_patient.lambda_handler
      Events:
        GetPatient:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /patients/{patient_id}
            Method: get
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref PatientsTable

  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/auth/
      Handler: auth.lambda_handler
      Events:
        Login:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /auth/login
            Method: post
            Auth:
              Authorizer: NONE
        Register:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /auth/register
            Method: post
            Auth:
              Authorizer: NONE

Outputs:
  ApiGatewayUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/'
  
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
  
  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient